fos_ck_editor:
    configs:
        my_config_1:
            toolbar: "my_toolbar_1"
            uiColor: "#e2e2e2"
        my_config_2:
            toolbar: "my_toolbar_2"
            uiColor: "#e2e2e2"
    toolbars:
        configs:
            my_toolbar_1: [ [ "BulletedList", "Undo", "Redo","SelectAll"] ]
            my_toolbar_2: [ [ "NumberedList", "Undo", "Redo","SelectAll"] ]

  
twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
