sonata_admin:
    title: 'Foodie'
    title_logo: build/images/logo.svg
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        legacy_twig_text_extension: false

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]